# =====================================================
# PLOT TOPIC SHARE OVER TIME
# Visualizes topic prevalence from LDA topic time series
# =====================================================
"""
Plot Topic Share Over Time

Loads the topic_time_series.csv file generated by LDA_Script.py
and creates visualizations showing how topic shares evolve over time.

Usage:
    python plot_topic_share.py
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# =====================================================
# CONFIGURATION
# =====================================================
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

output_dir = BASE_DIR / "data" / "processed"
output_dir.mkdir(parents=True, exist_ok=True)
topic_ts_file = output_dir / "topic_time_series.csv"

# Plot settings
PLOT_STYLE = "seaborn-v0_8-darkgrid"  # or "default", "seaborn", etc.
FIG_SIZE = (14, 8)
DPI = 100

# Topic names mapping
TOPIC_NAMES = {
    0: "Platform Administration",
    1: "Bitcoin Operation Mechanics",
    2: "Trading Behaviour",
    3: "Bitcoin Ideology",
    4: "General Sentiment"
}

# =====================================================
# LOAD DATA
# =====================================================
print("="*60)
print("LOADING TOPIC TIME SERIES DATA")
print("="*60)

if not topic_ts_file.exists():
    raise FileNotFoundError(
        f"Topic time series file not found: {topic_ts_file}\n"
        f"Please run LDA_Script.py first to generate the data."
    )

print(f"Loading from: {topic_ts_file}")
df = pd.read_csv(topic_ts_file)

# Parse date column
df["date"] = pd.to_datetime(df["date"])

print(f"  - Loaded {len(df):,} days")
print(f"  - Date range: {df['date'].min()} to {df['date'].max()}")
print(f"  - Columns: {df.columns.tolist()}")

# Extract topic columns (theta_k_sum or theta_k_mean)
# We'll use theta_k_mean for "share" (proportion) or theta_k_sum for "intensity"
use_mean = True  # Set to False to use sum instead

if use_mean:
    topic_cols = [c for c in df.columns if c.endswith("_mean") and c.startswith("theta_")]
    ylabel = "Topic Share (Mean Proportion)"
    title_suffix = "Topic Share"
else:
    topic_cols = [c for c in df.columns if c.endswith("_sum") and c.startswith("theta_")]
    ylabel = "Topic Intensity (Sum of Proportions)"
    title_suffix = "Topic Intensity"

# Sort columns to ensure consistent ordering
topic_cols = sorted(topic_cols, key=lambda x: int(x.split("_")[1]))

print(f"\n  - Found {len(topic_cols)} topics")
print(f"  - Using: {'mean' if use_mean else 'sum'} columns")

# =====================================================
# PLOT 1: Stacked Area Chart (Topic Share Over Time)
# =====================================================
print("\n" + "="*60)
print("CREATING PLOTS")
print("="*60)

plt.style.use(PLOT_STYLE)
fig, axes = plt.subplots(2, 1, figsize=FIG_SIZE, dpi=DPI)

# Plot 1: Stacked area chart
ax1 = axes[0]
colors = plt.cm.Set3(np.linspace(0, 1, len(topic_cols)))

# Prepare data for stacked plot
plot_data = df[["date"] + topic_cols].copy()
plot_data = plot_data.set_index("date").sort_index()

# Create stacked area plot
topic_num_0 = int(topic_cols[0].split("_")[1])
topic_name_0 = TOPIC_NAMES.get(topic_num_0, f"Topic {topic_num_0}")
ax1.fill_between(
    plot_data.index,
    0,
    plot_data[topic_cols[0]],
    label=topic_name_0,
    color=colors[0],
    alpha=0.7
)

bottom = plot_data[topic_cols[0]].values
for i, col in enumerate(topic_cols[1:], 1):
    topic_num = int(col.split("_")[1])
    topic_name = TOPIC_NAMES.get(topic_num, f"Topic {topic_num}")
    ax1.fill_between(
        plot_data.index,
        bottom,
        bottom + plot_data[col].values,
        label=topic_name,
        color=colors[i],
        alpha=0.7
    )
    bottom = bottom + plot_data[col].values

ax1.set_xlabel("Date", fontsize=12)
ax1.set_ylabel(ylabel, fontsize=12)
ax1.set_title(f"Topic Share Over Time - Stacked Area Chart", fontsize=14, fontweight="bold")
ax1.legend(loc="upper left", ncol=min(len(topic_cols), 5), fontsize=9)
ax1.grid(True, alpha=0.3)
ax1.tick_params(axis="x", rotation=45)

# Format x-axis dates
fig.autofmt_xdate()

# Plot 2: Individual line plots
ax2 = axes[1]
for i, col in enumerate(topic_cols):
    topic_num = int(col.split("_")[1])
    topic_name = TOPIC_NAMES.get(topic_num, f"Topic {topic_num}")
    ax2.plot(
        plot_data.index,
        plot_data[col],
        label=topic_name,
        color=colors[i],
        linewidth=2,
        alpha=0.8
    )

ax2.set_xlabel("Date", fontsize=12)
ax2.set_ylabel(ylabel, fontsize=12)
ax2.set_title(f"Topic Share Over Time - Individual Topics", fontsize=14, fontweight="bold")
ax2.legend(loc="best", ncol=min(len(topic_cols), 5), fontsize=9)
ax2.grid(True, alpha=0.3)
ax2.tick_params(axis="x", rotation=45)

plt.tight_layout()

# Save plot
output_plot = output_dir / "topic_share_over_time.png"
plt.savefig(output_plot, dpi=DPI, bbox_inches="tight")
print(f"✅ Saved plot to: {output_plot}")

# =====================================================
# PLOT 2: Individual Topic Plots (Subplots)
# =====================================================
n_topics = len(topic_cols)
n_cols = 3
n_rows = (n_topics + n_cols - 1) // n_cols

fig2, axes2 = plt.subplots(n_rows, n_cols, figsize=(15, 4*n_rows), dpi=DPI)
axes2 = axes2.flatten() if n_topics > 1 else [axes2]

for i, col in enumerate(topic_cols):
    ax = axes2[i]
    topic_num = int(col.split("_")[1])
    topic_name = TOPIC_NAMES.get(topic_num, f"Topic {topic_num}")
    ax.plot(
        plot_data.index,
        plot_data[col],
        color=colors[i],
        linewidth=2
    )
    ax.set_title(topic_name, fontsize=12, fontweight="bold")
    ax.set_xlabel("Date", fontsize=10)
    ax.set_ylabel(ylabel, fontsize=10)
    ax.grid(True, alpha=0.3)
    ax.tick_params(axis="x", rotation=45)

# Hide unused subplots
for i in range(n_topics, len(axes2)):
    axes2[i].axis("off")

plt.suptitle("Individual Topic Shares Over Time", fontsize=16, fontweight="bold", y=0.995)
plt.tight_layout()

output_plot2 = output_dir / "topic_share_individual.png"
plt.savefig(output_plot2, dpi=DPI, bbox_inches="tight")
print(f"✅ Saved individual plots to: {output_plot2}")

# =====================================================
# PLOT 3: Heatmap (Topic Share by Month)
# =====================================================
# Create monthly aggregation
df_monthly = df.copy()
df_monthly["year_month"] = df_monthly["date"].dt.to_period("M")

monthly_agg = df_monthly.groupby("year_month")[topic_cols].mean()

# Create heatmap
fig3, ax3 = plt.subplots(figsize=(12, 6), dpi=DPI)

im = ax3.imshow(
    monthly_agg.T,
    aspect="auto",
    cmap="YlOrRd",
    interpolation="nearest"
)

# Set ticks and labels
ax3.set_xticks(range(len(monthly_agg.index)))
ax3.set_xticklabels([str(x) for x in monthly_agg.index], rotation=45, ha="right")
ax3.set_yticks(range(len(topic_cols)))
topic_labels = [TOPIC_NAMES.get(int(col.split("_")[1]), f"Topic {int(col.split('_')[1])}") 
                for col in topic_cols]
ax3.set_yticklabels(topic_labels)

# Add colorbar
cbar = plt.colorbar(im, ax=ax3)
cbar.set_label(ylabel, fontsize=11)

ax3.set_xlabel("Month", fontsize=12)
ax3.set_ylabel("Topic", fontsize=12)
ax3.set_title("Topic Share Heatmap by Month", fontsize=14, fontweight="bold")

plt.tight_layout()

output_plot3 = output_dir / "topic_share_heatmap.png"
plt.savefig(output_plot3, dpi=DPI, bbox_inches="tight")
print(f"✅ Saved heatmap to: {output_plot3}")

# =====================================================
# SUMMARY STATISTICS
# =====================================================
print("\n" + "="*60)
print("TOPIC SHARE SUMMARY STATISTICS")
print("="*60)

summary_stats = []
for i, col in enumerate(topic_cols):
    topic_num = int(col.split("_")[1])
    topic_name = TOPIC_NAMES.get(topic_num, f"Topic {topic_num}")
    stats = {
        "Topic": topic_name,
        "Mean": plot_data[col].mean(),
        "Std": plot_data[col].std(),
        "Min": plot_data[col].min(),
        "Max": plot_data[col].max(),
        "Trend": "↑" if plot_data[col].iloc[-1] > plot_data[col].iloc[0] else "↓"
    }
    summary_stats.append(stats)

summary_df = pd.DataFrame(summary_stats)
print("\n" + summary_df.to_string(index=False))

# Save summary
summary_file = output_dir / "topic_share_summary.csv"
summary_df.to_csv(summary_file, index=False)
print(f"\n✅ Saved summary statistics to: {summary_file}")

# =====================================================
# COMPLETE
# =====================================================
print("\n" + "="*60)
print("PLOTTING COMPLETE")
print("="*60)
print(f"\nGenerated plots:")
print(f"  1. {output_plot}")
print(f"  2. {output_plot2}")
print(f"  3. {output_plot3}")
print(f"\nSummary statistics saved to: {summary_file}")

plt.show()

